### ISSUE TITLE
rpm install erase %config(noreplace) file

### ISSUE THREAD

**Issue by guillaumevincent** [redhat-cip/dci-ui#36]
During the installation of the RPM file, it seems that the config.js file is replaced even if the file is marked as `%config(noreplace)`

see https://github.com/redhat-cip/dci-ui/blob/master/dci-ui.spec#L40

@dsavineau think about a problem between the symbolic link, the cp and the noreplace:

```
%install
install -d -m0755 %{buildroot}/srv/www/dci-ui
install -d -m0755 %{buildroot}/etc/dci-ui
cp -r static/* %{buildroot}/srv/www/dci-ui
ln -sf /srv/www/dci-ui/config.js %{buildroot}/etc/dci-ui/config.js

%files
/srv/www/dci-ui/*
%config(noreplace) /etc/dci-ui/config.js
```

The problem is during the deployment of dci-ui, config.js file is not valid between `yum update` and the [ansible config.js configuration](https://github.com/redhat-cip/dci-infra/blob/master/roles/dci-ui/tasks/main.yml#L36)

```
- name: Configure dci-ui config.js
  template:
    src: config.js.j2
    dest: /etc/dci-ui/config.js
  notify:
    - reload httpd
  tags:
- dci-core
```
